areas:
  filename: /Users/aniquatabassum/Downloads/studies/Undergrad Thesis/SuverySetDivide/JMetal/merged.csv
  distance_filename: /Users/aniquatabassum/Downloads/studies/Undergrad Thesis/SuverySetDivide/JMetal/distances.csv

